### ISSUE TITLE
filed nodes and weights which in hashring need a  Mutex?

### ISSUE THREAD

**Issue by barryz** [g4zhuj/hashring#1]
Nodes and weights which in hashring need a  Mutex to support thread-safe guarantee?

**Comment by g4zhuj** [comment]
fixed.

**Comment by barryz** [comment]
https://github.com/g4zhuj/hashring/blob/master/hashring.go#L46  `sync.RWMutex`  can be used directly after declaration, no assignment is required 😃

**Comment by g4zhuj** [comment]
ha.ha.. you are right.
